server:
  port: 8400

spring:
  application:
    name: payment-service

  datasource:
    url: jdbc:mysql://localhost:3306/payment_db?createDatabaseIfNotExist=true
    username: austin
    password: austinmysql

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      acks: all
      retries: 3
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer


order-service:
  base-url: http://localhost:8300

internal:
  service-token: delivery-internal-secret-token


outbox:
  payment-completed-topic: payment.completed