server:
  port: 8300

spring:
  application:
    name: order-service

  datasource:
    url: jdbc:mysql://localhost:3306/order_db?createDatabaseIfNotExist=true
    username: austin
    password: austinmysql

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  internal:
    service-token: delivery-internal-secret-token

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: order-service
      auto-offset-reset: earliest

  topics:
    payment-completed: payment.completed