server:
  port: 8200

spring:
  application:
    name: store-service

order-service:
  url: http://localhost:8300


  datasource:
    url: jdbc:mysql://localhost:3306/store_db?createDatabaseIfNotExist=true
    username: austin
    password: austinmysql

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      acks: all
      retries: 3
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
